# Header
menu:
  主页: /
  所有文章: /archives
  # 项目: /projects
  # 书籍: /books
# SubNav
subnav:
  github: "https://github.com/colin1994"
  weibo: "http://www.weibo.com/u/3171165012"
  rss: /rss2.xml
  mail: "mailto:hitwhylz@163.com"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"



# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: http://7xkc7a.com1.z0.glb.clouddn.com/author.png

#你的头像url
avatar: "http://7xkc7a.com1.z0.glb.clouddn.com/author.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: colin1994
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  OneV's Den: http://www.onevcat.com/
  唐巧的技术博客: http://blog.devtang.com/
  sunnyxx的技术博客: http://blog.sunnyxx.com/archives/
  objc中国: http://objccn.io/
  Big Nerd Ranch: https://www.bignerdranch.com/blog/
  NSHipster: http://nshipster.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是余龙泽(@Colin__丶), 就读于哈尔滨工业大学, 软件工程专业, 目前大四。在iOS学习道路上不断努力中。

#打赏
donate:
  enable: true
  text: Enjoy it ? Donate me !  欣赏此文？求鼓励，求支持！
  wechat: http://7xkc7a.com1.z0.glb.clouddn.com/wechatImage.png
  alipay: http://7xkc7a.com1.z0.glb.clouddn.com/alipayImage.png
  web: false