# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Colin's Nest
subtitle:
description:
author: Colin丶
email:
language: zh-Hans

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://http://colin1994.github.io
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
plugin:
- hexo-generator-feed

#Feed Atom
feed:
  type: rss2
  path: rss2.xml
  limit: 20
  hub:

## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: even
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:colin1994/colin1994.github.io.git
  branch: master




# # Next 主题配置
# # 站内搜索tinysou http://tinysou.com/
# #tinysou_Key: d4ab1eac98f4d5235098
# # baidusearch_key: djdjdjdjdj

# # swiftype_key
# swiftype_key: # your swiftype_key 如果没有填，则不启动该搜索


# ## 多说评论
# duoshuo_shortname: colin1994

# # 社交链接，将在侧栏中显示 均填写 url 即可
# social:
#   github: "https://github.com/colin1994"
#   weibo: "http://www.weibo.com/u/3171165012"
#   mail: "mailto:hitwhylz@163.com"

# # links name 友情链接的配置
# links_title: Links
# links:
#   OneV's Den: http://www.onevcat.com/
#   唐巧的技术博客: http://blog.devtang.com/
#   sunnyxx的技术博客: http://blog.sunnyxx.com/archives/
#   objc中国: http://objccn.io/
#   Big Nerd Ranch: https://www.bignerdranch.com/blog/
#   NSHipster: http://nshipster.com/

# # Creative Commons 4.0 International License.
# # http://creativecommons.org/
# # Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# creative_commons: by-nc-sa

# ## 文章末尾是否显示打赏按钮
# donate:
#   enable: true
#   text: Enjoy it ? Donate me !  欣赏此文？求鼓励，求支持！
#   alipay: http://7xkc7a.com1.z0.glb.clouddn.com/alipay2.png
#   wechat: http://7xkc7a.com1.z0.glb.clouddn.com/wechat1.png
